# Generated by Django 4.0.4 on 2022-07-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('video_type', models.CharField(max_length=255)),
            ],
        ),
    ]
