# Generated by Django 4.0.6 on 2022-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('duration_in_seconds', models.IntegerField()),
                ('video_type', models.CharField(max_length=255)),
            ],
        ),
    ]
