# Generated by Django 4.0.6 on 2022-07-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_videocharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='size',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
    ]
